services:
    alfredoramos.simplespoiler.helper:
        class: alfredoramos\simplespoiler\includes\helper
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'

    alfredoramos.simplespoiler.listener:
        class: alfredoramos\simplespoiler\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '@alfredoramos.simplespoiler.helper'
